strategy_name: DemoStrategy         # 策略名称
class_name: 'Demo'                  # 启动类名, 也就是策略任务类名，唯一
notices:
  - type: email
#    mailSmtpHost: 'smtp.exmail.qq.com'  # 如过是qq邮箱则这三行的内容无需填写
#    mailSmtpPort: '465'
#    mailSmtpSocketFactoryPort: '465'
    username: 'xxx@xxx.com'
    password: 'password'
    to: 'you@yourmail.com'
  - type: telegram
    token: '1234123:AAFs'    # 如需发电报通知 则需Token
    chatId: '-1232145235'     # 发电报通知用群GroupID
configs:                            # 策略配置需要的参数
  loop: 0.5                         # 多少秒定期执行 loop 函数  如不配置默认1秒。
  e:                                # 交易所的配置方式 如果配置名为e 则写程序的时候可以直接调用e
    name: okexv3
    symbol: BTC_USDT
    access: publicKey_Passphrase   # OkexV3 需要在公钥后加 "_你的Passphrase"
    secret: privateKey
  huobiex:                         # 配置了一个名字为huobiex的交易所
    name: huobipro
    symbol: BTC_USDT
    access: publicKey
    secret: privateKey
  exchanges:                      # 交易所数组的配置方式
    - name: okexv3
      symbol: EOS_BTC
      access: publicKey_Passphrase
      secret: privateKey
    - name: huobipro
      symbol: XRP_BTC
      access: publicKey
      secret: privateKey
  myString: Hello GOAi            # 自定义字符串
